### ISSUE TITLE
IOS 12.4.9 Buttons in UI not working

### ISSUE THREAD

**Issue by Axos11** [andi34/PhotoSwipe#13]
Hello andi34,

first of all thanks for maintaining this repository!

I implemented v4.4 of photoswipe in my project and noticed whilst debugging on an older ios device that the buttons in the opened lightbox in the top bar were not working at all. I then tried the same on the official photoswipe page. And there everything worked as expected. So i replaced every single file in your pen to find out if it is an css or js issue. As soon as i swapped both js files to 4.1.3 everything was working again. would you have any suggestions how to address this issue?

https://codepen.io/axos11/pen/NWbNGGK

Regards,
Martin

**Comment by mjau-mjau** [comment]
I also experienced this (it's been reported by users), although I first thought it was related to some of my own customizations. Basically the topbar buttons don't respond on iPhone 6 / iOS 12.5 (and older). This happens to coincide with missing **pointer-events** feature on iOS 12.5, which is used in Photoswipe. Pointer-events are supported in all modern browsers, and iOS 13+.
https://caniuse.com/pointer

I'm also very eager to find a fix for this issue. I'd have to start comparing original Photoswipe vs this fork, but I don't even have an older iOS device for testing 😟

**Comment by andi34** [comment]
Hey! Sorry, I am currently not very active because of private life stuff and don't have any iOS devices to test.

I'd suggest you'll clone my repo, and reset one commit and build the dist files and test again until it works for you. Let me know the latest commit where it works.

To reset one commit run `git reset --hard HEAD^` - I know this is a quite dirty solution, but guess the quickest way to find the breaking change for you.

**Comment by Axos11** [comment]
Hey, I debugged it and the issue started with 4.3 and its actually in line 3137 (photoswipe.js)

`if (!_moved && !_isMultitouch && !_numAnimations) {`
was changed to
`if (!_moved && !_isMultitouch && !_numAnimations && self.container.contains(e.target)) {`

If you just switch that line back in 4.4 everything goes back to normal on IOS 12.5 (Iphone 6)

Maybe you can tell me if there is some functionality going away with that change or something else is broken by it?

Regards, Martin

**Comment by mjau-mjau** [comment]
Good find @Axos11. I actually had that code section commented `// todo: iPhone bug?`, but I guess I forgot about it since it works with iOS 13+ (available for iPhone 7 and above).

That fix is from https://github.com/dimsemenov/PhotoSwipe/pull/1708, which fixes issues where clicking the close button also clicks buttons that are behind photoswipe https://github.com/dimsemenov/PhotoSwipe/issues/1608. Here is the commit https://github.com/andi34/PhotoSwipe/commit/55d031631096cc79cd05ceb37d543512659c733c

The fix involves using [Node.contains()](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) to make sure the clicked element is inside the `.pswp__container`. It's unclear why this fails on iOS 12.5 (and older), but it coincides with missing support for [Pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events).

```javascript
if (!_moved && !_isMultitouch && !_numAnimations && self.container.contains(e.target)) {
```

Removing the fix would be relatively harmless, although you risk having buttons in the background (behind Photoswipe) getting triggered when you click the close button. It could be the original issue only occurs for older devices without support for Pointer-events, hard to say.

If you have iPhone 6 / iOS 12.5 available for testing and can debug with console, I would personally like to understand why `self.container.contains(e.target)` fails on this platform:

```javascript
console.log(e.target, self.container, self.container.contains(e.target));
if (!_moved && !_isMultitouch && !_numAnimations && self.container.contains(e.target)) {
```

One could probably "patch" the fix so that it only applies if pointer-events are supported:
```javascript
if (!_moved && !_isMultitouch && !_numAnimations && (!_pointerEventEnabled || self.container.contains(e.target))) {
```

Another suggestion that was made https://github.com/dimsemenov/PhotoSwipe/issues/1608#issuecomment-660606641, might be a better solution for the original issue, preventing the even from bubbling.
```javascript 
// e.initCustomEvent(type, canBubble, cancelable, detail);
// e.initCustomEvent( 'pswpTap', true, true, eDetail );  // original
e.initCustomEvent( 'pswpTap', false, true, eDetail ); // fix
```

I don't have access to iOS 12.5, so I can't test these things, but we had a few clients who reported the issue. Of course, the easy fix is to remove the original fix, which should be mostly harmless.

**Comment by Axos11** [comment]
`if (!_moved && !_isMultitouch && !_numAnimations && (!_pointerEventEnabled || self.container.contains(e.target))) {`

That "fix" is as expected actually working.

I#m sorry but i can't help there atm. I have just an IOS Device, code on windows but have no actual debugging setup with console access in place. Maybe someone else has?
